const BMIN = 1;
const BMAX = 15;
const IMIN = 16;
const IMAX = 30;
const NMIN = 31;
const NMAX = 45;
const GMIN = 46;
const GMAX = 60;
const OMIN = 61;
const OMAX = 75;
const HORIZONTAL = 5;
const VERTICAL = 5;
const NUMBERMIN = 1;
const NUMBERMAX = 75;
var numbersCalled = [];
var bingoCard = [];
export{numbersCalled, NUMBERMIN, NUMBERMAX, bingoCard, BMIN,BMAX,IMIN,IMAX,NMIN,NMAX,GMIN,GMAX,OMIN,OMAX, HORIZONTAL, VERTICAL};